eShopSolution.AdminApp/Controllers/Components/PagerViewComponent.cs
using eShopSolution.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eShopSolution.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PageResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

eShopSolution.AdminApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using eShopSolution.AdminApp.Services;
using eShopSolution.ViewModels.System;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;

namespace eShopSolution.AdminApp.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IConfiguration _configuration;
        public LoginController(IUserApiClient userApiClient, IConfiguration configuration)
        {
            _userApiClient = userApiClient;
            _configuration = configuration;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            //logout session cũ;
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            //logout session cũ;
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("Token");
            return RedirectToAction("Index", "Login");
        }
        [HttpPost]
        public async Task<IActionResult> Index(LoginRequest request)
        {
            if (!ModelState.IsValid)
                return View(ModelState);
            var token = await _userApiClient.Authenticate(request);
            
            var userPrincipal = this.ValidateToken(token.Message);
            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                IsPersistent = false
            };

            HttpContext.Session.SetString("Token", token.Message);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(userPrincipal), authProperties);

            return RedirectToAction("Index", "Home");
        }

        private ClaimsPrincipal ValidateToken(string jwtToken)
        {
            IdentityModelEventSource.ShowPII = true;

            SecurityToken validatedToken;
            TokenValidationParameters validationParameters = new TokenValidationParameters();

            validationParameters.ValidateLifetime = true;

            validationParameters.ValidAudience = _configuration["Tokens:Issuer"];
            validationParameters.ValidIssuer = _configuration["Tokens:Issuer"];
            validationParameters.IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["Tokens:Key"]));

            ClaimsPrincipal principal = new JwtSecurityTokenHandler().ValidateToken(jwtToken, validationParameters, out validatedToken);

            return principal;
        }
    }
}

eShopSolution.AdminApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net.WebSockets;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using eShopSolution.AdminApp.Services;
using eShopSolution.ViewModels.Common;
using eShopSolution.ViewModels.System;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;

namespace eShopSolution.AdminApp.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IConfiguration _configuration;
        private readonly IRoleApiClient _roleApiClient;
        public UserController(IUserApiClient userApiClient,IConfiguration configuration,IRoleApiClient roleApiClient)
        {
            _userApiClient = userApiClient;
            _configuration = configuration;
            _roleApiClient = roleApiClient;
        }
        public async Task<IActionResult> Index(string keyWord,int pageIndex = 1, int pageSize = 1)
        {
            var sessoion = HttpContext.Session.GetString("Token");
            var requset = new GetUserPagingRequest()
            {
                BearerToken = sessoion,
                Keyword = keyWord,
                pageIndex = pageIndex,
                pageSize = pageSize
            };
            var data = await _userApiClient.GetUserPaging(requset);
            ViewBag.KeyWord = keyWord;
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }    
            return View(data.ResultObject);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RegisterRequest request)
        {
            if (!ModelState.IsValid)
                return View(ModelState);
            var result = await _userApiClient.RegisterUser(request);
            if(result.IsSuccessed)
            {
                TempData["result"] = "success";
                return RedirectToAction("Index");
            }    
            ModelState.AddModelError("", result.Message);
            return View(request);
            
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View(ModelState);
            var result = await _userApiClient.UpdateUser(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "success";
                return RedirectToAction("Index", "User");
            }
            ModelState.AddModelError("", result.Message);
            return View(request);

        }
        [HttpGet]
        public async Task<IActionResult> Update(Guid userId)
        {
            //var user = _userApiClient
            var result = await _userApiClient.GetUserById(userId);
            if (result.IsSuccessed)
                return View(result.ResultObject);
            return RedirectToAction("Index", "User");

        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid Id)
        {
            var result = await _userApiClient.GetUserById(Id);
            return View(result.ResultObject);
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            return View(new UserDeleteRequest()
            {
                Id = id
            });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UserDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View(ModelState);
            var result = await _userApiClient.DeleteUser(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "success";
                return RedirectToAction("Index", "User");
            }
            ModelState.AddModelError("", result.Message);
            return View(request);

        }

        [HttpGet]
        public async Task<IActionResult> RoleAssign(Guid id)
        {
            var roleAssignRequest = await GetRoleAssignRequest(id);

                return View(roleAssignRequest);
            

        }

        [HttpPost]
        public async Task<IActionResult> RoleAssign(RoleAssignRequest request)
        {
            if (!ModelState.IsValid)
                return View(ModelState);
            var result = await _userApiClient.RoleAssign(request.Id, request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Cập nhật quyền thành công";
                return RedirectToAction("Index", "User");
            }
            ModelState.AddModelError("", result.Message);
            var roleAssignRequest =await GetRoleAssignRequest(request.Id);

            return View(roleAssignRequest);
          //  return View(request);

        }
        private async Task<RoleAssignRequest> GetRoleAssignRequest(Guid id)
        {
            var result = await _userApiClient.GetUserById(id);
            var roles = await _roleApiClient.GetAll();
            var roleAssignRequest = new RoleAssignRequest();
            List<SelectItem> RolesAdd = new List<SelectItem>();
            foreach (var roleName in roles.ResultObject)
            {
                
                SelectItem addSelec = new SelectItem()
                {
                    Id = roleName.Id.ToString(),
                    Name = roleName.Name,
                    Selected = result.ResultObject.RoleAssign.Contains(roleName.Name)

                };
                RolesAdd.Add(addSelec);
                roleAssignRequest.Id = roleName.Id;
               


                roleAssignRequest.Roles = RolesAdd;

            }
            return roleAssignRequest;
        }

        private ClaimsPrincipal ValidateToken(string jwtToken)
        {
            IdentityModelEventSource.ShowPII = true;

            SecurityToken validatedToken;
            TokenValidationParameters validationParameters = new TokenValidationParameters();

            validationParameters.ValidateLifetime = true;

            validationParameters.ValidAudience = _configuration["Tokens:Issuer"];
            validationParameters.ValidIssuer = _configuration["Tokens:Issuer"];
            validationParameters.IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["Tokens:Key"]));

            ClaimsPrincipal principal = new JwtSecurityTokenHandler().ValidateToken(jwtToken, validationParameters, out validatedToken);

            return principal;
        }

    }
}

eShopSolution.AdminApp/Views/User/Create.cshtml
@model eShopSolution.ViewModels.System.RegisterRequest

@{
    ViewData["Title"] = "Tạo mới người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    
<h1>Create</h1>

<div class="row">
    <div class="col-12">
        <div class="page-title-box">

            <div class="page-title-left">
                <ol class="breadcrumb p-0 m-0" style="float:left !important">
                    @*<li class="breadcrumb-item"><a href="#">Velonic</a></li>*@
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Tạo mới người dùng</li>
                </ol>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <button class="btn btn-success" asp-action="Index" asp-controller="User">Về danh sách</button>
            </div>
            <div class="card-body">
                <h4 class="header-title mb-4">Register Request</h4>
                <form asp-action="Create" asp-controller="User" class="parsley-examples" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Dob" class="control-label"></label>
                        <input asp-for="Dob" class="form-control" />
                        <span asp-validation-for="Dob" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserName" class="control-label"></label>
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ComfirmPassword" class="control-label"></label>
                        <input asp-for="ComfirmPassword" class="form-control" />
                        <span asp-validation-for="ComfirmPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Lưu lại" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    @*<div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Dob" class="control-label"></label>
                    <input asp-for="Dob" class="form-control" />
                    <span asp-validation-for="Dob" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ComfirmPassword" class="control-label"></label>
                    <input asp-for="ComfirmPassword" class="form-control" />
                    <span asp-validation-for="ComfirmPassword" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>*@
</div>

eShopSolution.AdminApp/Views/User/Delete.cshtml
@model eShopSolution.ViewModels.System.UserDeleteRequest

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserDeleteRequest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input asp-for="Id" type="hidden" class="form-control" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

eShopSolution.AdminApp/Views/User/Details.cshtml
@model eShopSolution.ViewModels.System.UserUpdateRequest

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>UserUpdateRequest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dob)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dob)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

eShopSolution.AdminApp/Views/User/Index.cshtml
@using eShopSolution.ViewModels.Common;
@model PagedResult<eShopSolution.ViewModels.System.UserViewModel>

@{
    ViewData["Title"] = "Danh sách người dùng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
        
    </script>

    }
    @*<p>
            <a asp-action="Create">Create New</a>
        </p>*@
    <h4><b>Danh sách người dùng</b></h4>
    <div class="row">
        <div class="col-12">

            <div class="page-title-box">
                <div class="page-title-left">
                    <ol class="breadcrumb p-0 m-0" style="float:left !important">
                        @*<li class="breadcrumb-item"><a href="#">Velonic</a></li>*@
                        <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Danh sách người dùng</li>
                    </ol>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="card-header">
        <button class="btn btn-success" asp-action="Create" asp-controller="User">Tạo mới</button>
        <form asp-action="Index" method="get">

            <input type="text" class=" form-control" value="@ViewBag.KeyWord" name="keyWord" />
            <button type="submit" value="Tìm" class="btn btn-primary">Tìm</button>
            <button type="button" onclick="window.location.href='User/Index'" class="btn btn-primary">Reset</button>
        </form>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="row">
                    <div class="col-md-6">
                        @if (ViewBag.Success != null)
                        {
                            <div id="msgAlert" class="alert alert-success" role="alert">
                                @ViewBag.SuccessMsg
                            </div>
                        }
                    </div>
                </div>
               
                <div class="card-body table-responsive">

                    <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">

                        <thead>
                            <tr>
                                @*<th>ID</th>*@
                                <th>FirstName</th>
                                <th>LastName</th>
                                <th>Phone</th>
                                <th>UserName</th>
                                <th>Email</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach (var item in Model.Items)
                            {
                                <tr>
                                    @*<td>
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </td>*@
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FirstName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LasttName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Email)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Sửa", "Update", new { userId = item.Id }) |
                                        @Html.ActionLink("Xem", "Details", new { Id = item.Id }) |
                                        @Html.ActionLink("Xóa", "Delete", new { id = item.Id }) |
                                        @Html.ActionLink("Phân quyền", "RoleAssign", new { id = item.Id })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @await Component.InvokeAsync("Pager", Model)
                </div>
            </div>
        </div>
    </div>

eShopSolution.AdminApp/Views/User/Login.cshtml
@model eShopSolution.ViewModels.System.LoginRequest
@{
    Layout = null;
}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Đăng nhập hệ thống</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Responsive bootstrap 4 admin template" name="description">
    <meta content="Coderthemes" name="author">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- App favicon -->
    <link rel="shortcut icon" href="assets\images\favicon.ico">

    <!-- App css -->
    <link href="\assets\css\bootstrap.min.css" rel="stylesheet" type="text/css" id="bootstrap-stylesheet">
    <link href="\assets\css\icons.min.css" rel="stylesheet" type="text/css">
    <link href="\assets\css\app.min.css" rel="stylesheet" type="text/css" id="app-stylesheet">

</head>

<body class="authentication-page">

    <div class="account-pages my-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="card mt-4">
                        <div class="card-header p-4 bg-primary">
                            <h4 class="text-white text-center mb-0 mt-0">Velonic</h4>
                        </div>
                        <div class="card-body">
                            <form  class="p-2" asp-action="Login" asp-controller="User" method="post">

                                <div class="form-group mb-3">
                                    <label for="emailaddress">Tài khoản :</label>
                                    <input class="form-control" type="text" asp-for="UserName" required="" placeholder="Nhập Tài khoản...">
                                </div>

                                <div class="form-group mb-3">
                                    <label for="password">Mật khẩu :</label>
                                    <input class="form-control" type="password" required="" asp-for="Password" placeholder="Nhập Mật khẩu...">
                                </div>

                                <div class="form-group mb-4">
                                    <div class="checkbox checkbox-success">
                                        <input asp-for="RemmemberMe" type="checkbox" checked="">
                                        <label for="remember">
                                            Remember me
                                        </label>
                                        <a href="/User/ForgotPassword" class="text-muted float-right">Quên mật khẩu?</a>
                                    </div>
                                </div>

                                <div class="form-group row text-center mt-4 mb-4">
                                    <div class="col-12">
                                        <button class="btn btn-md btn-block btn-primary waves-effect waves-light" type="submit">Đăng nhập</button>
                                    </div>
                                </div>

                                <div class="form-group row mb-0">
                                    <div class="col-sm-12 text-center">
                                        <p class="text-muted mb-0">
                                            Liên hệ quản trị ^^
                                            @*Don't have an account?*@ 
                                        @*<a href="pages-register.html" class="text-dark m-l-5"><b>Sign Up</b></a>*@
                                        </p>
                                  
                                    </div>
                                </div>
                            </form>

                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->
                    <!-- end row -->

                </div>
                <!-- end col -->
            </div>
            <!-- end row -->

        </div>
    </div>

    <!-- Vendor js -->
    <script src="\assets\js\vendor.min.js"></script>

    <!-- App js -->
    <script src="\assets\js\app.min.js"></script>

</body>

</html>

eShopSolution.AdminApp/Views/User/RoleAssign.cshtml
@model eShopSolution.ViewModels.System.RoleAssignRequest

@{
    ViewData["Title"] = "RoleAssign";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>RoleAssign</h1>

<h4>RoleAssignRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RoleAssign">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            @for(var i = 0 ; i < Model.Roles.Count ; i++)
            {
                <div class="form-group">
                    <label>
                        @Model.Roles[i].Name
                        <input type="checkbox" asp-for="Roles[i].Selected" class="form-control" />
                        <input type="hidden" asp-for="Roles[i].Id" />
                        <input type="hidden" asp-for="Roles[i].Name" />
                    </label>
                    <span asp-validation-for="Roles[i].Name" class="text-danger"></span>
                </div>
            }

            <div class="form-group">
                <input type="submit" value="Lưu Lại" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>